# Generated by Django 5.1 on 2024-08-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchedulModel',
            new_name='ScheduleModel',
        ),
    ]
