# Generated by Django 5.1 on 2024-08-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_schedulmodel_schedulemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbermodel',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')]),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
